name: Entire-World-Loader
main: iieLoadSaveEntireWorld.Main
version: 4.0
author: TBMCPlugins
commands:
  beginfullmapload:
    description: ''
  stopfullmapload:
    description: loads and saves the entire map, in 32x32 chunk sections